### ISSUE TITLE
yawp_wim_widget_params change name not working?

### ISSUE THREAD

**Issue by yumyo** [Yapapaya/Widgets-In-Menu-for-WordPress#1]
While the above filter is triggered, it doesn't seems to have any effect trying to change widget name as displayed in admin. It is just intended to alter the front-end output? If yes, is there any other way to change the widget name in admin besides directly editing your plugins code?

**Comment by actual-saurabh** [comment]
Not yet, but if you can code, I'll gladly accept a pull request and give you contribution credits. Otherwise, I'm a little tied up at this moment and this could take a couple of weeks to get to.

**Comment by actual-saurabh** [comment]
In hindsight, @yumyo where are you hooking?

Because your hook won't work if it isn't hooked before the filter is called. This filter is run when this filter is run: https://github.com/yapapaya/Widgets-In-Menu-for-WordPress/blob/master/classes/class-yawp-wim-walker.php#L8
